version: '2'
services:
    plusbits-app:
        image: plusbits
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://plusbits-postgresql:5432/plusBits
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    plusbits-postgresql:
        extends:
            file: postgresql.yml
            service: plusbits-postgresql
